routes/web.php
<?php
    Route::get('/','UserController@home');
    Route::get('/wsMagia/{id}','MagiasController@ws');
    Route::resource('users', 'UserController');
    Route::resource('antecedentes', 'AntecedentesController');
    Route::resource('armaduras', 'ArmadurasController');
    Route::resource('armas', 'ArmasController');
    Route::resource('atributos', 'AtributosController');
    Route::resource('caracteristicas', 'CaracteristicasController');
    Route::resource('classes', 'ClassesController');
    Route::resource('definicoes', 'DefinicoesController');
    Route::resource('ficha', 'FichaController');
    Route::resource('itens', 'ItensController');
    Route::resource('magias', 'MagiasController');
    Route::resource('pericias', 'PericiasController');
    Route::resource('personalizacao', 'PersonalizacaoController');
    Route::resource('proficiencias', 'ProficienciasController');
    Route::resource('racas', 'RacasController');
    Route::resource('talentos', 'TalentosController');
    
    Auth::routes();
    
    // Social Auth
    Route::get('auth/social', 'Auth\SocialAuthController@show')->name('social.login');
    Route::get('oauth/{driver}', 'Auth\SocialAuthController@redirectToProvider')->name('social.oauth');
    Route::get('oauth/{driver}/callback', 'Auth\SocialAuthController@handleProviderCallback')->name('social.callback');
    Auth::routes();
    
    Route::get('/home', 'HomeController@index')->name('home');
    

resources/views/admin/armaduras_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Armadura</h2>
    @else 
    <h2> Alteração de Armadura </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('armaduras.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('armaduras.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('armaduras.update', $armad->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_armd">Nome:</label>
                <input type="text" class="form-control" id="nome_armd" 
                       name="nome_armd" 
                       value="{{$armad->nome_armd or old('nome_armd')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_armd">Descrição:</label>
                <input type="text" class="form-control" id="descricao_armd" 
                       name="descricao_armd" 
                       value="{{$armad->descricao_armd or old('descricao_armd')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="preco_armd">Preço:</label>
                <input type="text" class="form-control" id="preco_armd" 
                       name="preco_armd" 
                       value="{{$armad->preco_armd or old('preco_armd')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="peso_armd">Peso(Kg):</label>
                <input type="text" class="form-control" id="peso_armd" 
                       name="peso_armd" 
                       value="{{$armad->peso_armd or old('peso_armd')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="class_armad">Classe de Armadura:</label>
                <input type="text" class="form-control" id="class_armad" 
                       name="class_armad" 
                       value="{{$armad->class_armad or old('class_armad')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="forca">Força:</label>
                <input type="text" class="form-control" id="forca" 
                       name="forca" 
                       value="{{$armad->forca or old('forca')}}">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/armaduras_list.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-2'>
    <a href='{{route('armaduras.create')}}' class='btn btn-primary' 
       role='button'> Novo </a>
       </div>
<div class='col-sm-11'>
        <h2>Armaduras</h2>
    </div>
    
    <div class="col-sm-12">
        <table class="table table-striped">
        <thead>
        <tr>
          <th width="200px">Nome</th>
          <th>Descrição</th>
          <th width="235px">Ações</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($armad as $armd)
            <tr>
              <td>{{$armd->nome_armd}}</td>
              <td>{{$armd->descricao_armd}}</td>
              <td>
            
            <a href='{{route('armaduras.show',$armd->id)}}'
               class='btn btn-info' 
               role='button'> Detalhes </a> 

            <a href='{{route('armaduras.edit',$armd->id)}}'
               class='btn btn-warning' 
               role='button'> Alterar </a> 

            <form style="display: inline-block"
                  method="post"
                  action="{{route('armaduras.destroy',$armd->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="submit"
                        class="btn btn-danger"> Deletar </button>
            </form>
            </td>

              </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop   

resources/views/admin/armas_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Armas</h2>
    @else 
    <h2> Alteração de Armas </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('armas.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('armas.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('armas.update', $arma->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_arm">Nome:</label>
                <input type="text" class="form-control" id="nome_arm" 
                       name="nome_arm" 
                       value="{{$arma->nome_arm or old('nome_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_arm">Descrição:</label>
                <input type="text" class="form-control" id="descricao_arm" 
                       name="descricao_arm" 
                       value="{{$arma->descricao_arm or old('descricao_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="tipo_arm">Tipo:</label>
                <input type="text" class="form-control" id="tipo_arm" 
                       name="tipo_arm" 
                       value="{{$arma->tipo_arm or old('tipo_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="preco_arm">Preço:</label>
                <input type="text" class="form-control" id="preco_arm" 
                       name="preco_arm" 
                       value="{{$arma->preco_arm or old('preco_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="peso_arm">Peso(Kg):</label>
                <input type="text" class="form-control" id="peso_arm" 
                       name="peso_arm" 
                       value="{{$arma->peso_arm or old('peso_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="dano_arm">Dano:</label>
                <input type="text" class="form-control" id="dano_arm" 
                       name="dano_arm" 
                       value="{{$arma->dano_arm or old('dano_arm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="propiedade">Propiedade:</label>
                <input type="text" class="form-control" id="propiedade" 
                       name="propiedade" 
                       value="{{$arma->propiedade or old('propiedade')}}">
            </div>
            <div class="form-group">
                <label for="efeito_adicional">Efeito Adicional:</label>
                <input type="text" class="form-control" id="efeito_adicional" 
                       name="efeito_adicional" 
                       value="{{$arma->efeito_adicional or old('efeito_adicional')}}">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/classes_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Classe</h2>
    @else 
    <h2> Alteração de Classe </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('classes.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('classes.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('classes.update', $classes->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_cla">Nome:</label>
                <input type="text" class="form-control" id="nome_cla" 
                       name="nome_cla" 
                       value="{{$classes->nome_cla or old('nome_cla')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_cla">Descrição:</label>
                <input type="text" class="form-control" id="descricao_cla" 
                       name="descricao_cla" 
                       value="{{$classes->descricao_cla or old('descricao_cla')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="dado_vida">Dado de Vida:</label>
                <input type="text" class="form-control" id="dado_vida" 
                       name="dado_vida" 
                       value="{{$classes->dado_vida or old('dado_vida')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="truques">Truques:</label>
                <input type="text" class="form-control" id="truques" 
                       name="truques" 
                       value="{{$classes->truques or old('truques')}}">
            </div>
            <div class="form-group">
                <label for="nivel1">Nivel 1:</label>
                <input type="text" class="form-control" id="nivel1" 
                       name="nivel1" 
                       value="{{$classes->nivel1 or old('nivel1')}}">
            </div>
            <div class="form-group">
                <label for="nivel2">Nivel 2:</label>
                <input type="text" class="form-control" id="nivel2" 
                       name="nivel2" 
                       value="{{$classes->nivel2 or old('nivel2')}}">
            </div>
            <div class="form-group">
                <label for="nivel3">Nivel 3:</label>
                <input type="text" class="form-control" id="nivel3" 
                       name="nivel3" 
                       value="{{$classes->nivel3 or old('nivel3')}}">
            </div>
            <div class="form-group">
                <label for="nivel4">Nivel 4:</label>
                <input type="text" class="form-control" id="nivel4" 
                       name="nivel4" 
                       value="{{$classes->nivel4 or old('nivel4')}}">
            </div>
            <div class="form-group">
                <label for="nivel5">Nivel 5:</label>
                <input type="text" class="form-control" id="nivel5" 
                       name="nivel5" 
                       value="{{$classes->nivel5 or old('nivel5')}}">
            </div>
            <div class="form-group">
                <label for="nivel6">Nivel 6:</label>
                <input type="text" class="form-control" id="nivel6" 
                       name="nivel6" 
                       value="{{$classes->nivel6 or old('nivel6')}}">
            </div>
            <div class="form-group">
                <label for="nivel7">Nivel 7:</label>
                <input type="text" class="form-control" id="nivel7" 
                       name="nivel7" 
                       value="{{$classes->nivel7 or old('nivel7')}}">
            </div>
            <div class="form-group">
                <label for="nivel8">Nivel 8:</label>
                <input type="text" class="form-control" id="nivel8" 
                       name="nivel8" 
                       value="{{$classes->nivel8 or old('nivel8')}}">
            </div>
            <div class="form-group">
                <label for="nivel9">Nivel 9:</label>
                <input type="text" class="form-control" id="nivel9" 
                       name="nivel9" 
                       value="{{$classes->nivel9 or old('nivel9')}}">
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/classes_list.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-2'>
    <a href='{{route('classes.create')}}' class='btn btn-primary' 
       role='button'> Novo </a>
       </div>
<div class='col-sm-11'>
        <h2>Classes</h2>
    </div>
    
    <div class="col-sm-12">
        <table class="table table-striped">
        <thead>
        <tr>
          <th width="200px">Nome</th>
          <th>Descrição</th>
          <th width="235px">Ações</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($classes as $classe)
            <tr>
              <td>{{$classe->nome_cla}}</td>
              <td>{{$classe->descricao_cla}}</td>
              <td>
            
            <a href='{{route('classes.show',$classe->id)}}'
               class='btn btn-info' 
               role='button'> Detalhes </a> 

            <a href='{{route('classes.edit',$classe->id)}}'
               class='btn btn-warning' 
               role='button'> Alterar </a> 

            <form style="display: inline-block"
                  method="post"
                  action="{{route('classes.destroy',$classe->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="submit"
                        class="btn btn-danger"> Deletar </button>
            </form>
            </td>

              </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop   

resources/views/admin/classes_view.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-10'></div>
<div class='col-sm-2'>
    <a href="{{route('classes.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
    <div>
        <div class='col-sm-12'>
            <h2> Detalhes da Classe</h2>
            <p><b>ID: </b> {{$class->id}}</p>
            <p><b>Nome: </b> {{$class->nome_cla}}</p>
            <p><b>Descrição: </b> {{$class->descricao_cla}}</p>
            <p><b>Dado de vida: </b> {{$class->dado_vida}}</p>
            <p><b>Truques: </b> {{$class->truque}}</p>
            <p><b>Magias de Nível 1: </b> {{$class->nivel1}}</p>
            <p><b>Magias de Nível 2: </b> {{$class->nivel2}}</p>
            <p><b>Magias de Nível 3: </b> {{$class->nivel3}}</p>
            <p><b>Magias de Nível 4: </b> {{$class->nivel4}}</p>
            <p><b>Magias de Nível 5: </b> {{$class->nivel5}}</p>
            <p><b>Magias de Nível 6: </b> {{$class->nivel6}}</p>
            <p><b>Magias de Nível 7: </b> {{$class->nivel7}}</p>
            <p><b>Magias de Nível 8: </b> {{$class->nivel8}}</p>
            <p><b>Magias de Nível 9: </b> {{$class->nivel9}}</p>
            </div>
    </div>
@endsection

resources/views/admin/definicoes_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Definição</h2>
    @else 
    <h2> Alteração de Definição </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('definicoes.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('definicoes.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('definicoes.update', $defin->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="item">Item:</label>
                <input type="text" class="form-control" id="item" 
                       name="item" 
                       value="{{$defin->item or old('item')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="definicao">Definição:</label>
                <input type="text" class="form-control" id="definicao" 
                       name="definicao" 
                       value="{{$defin->definicao or old('definicao')}}"
                       required>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/itens_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Item</h2>
    @else 
    <h2> Alteração de Item </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('itens.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('itens.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('itens.update', $itens->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_itm">Nome:</label>
                <input type="text" class="form-control" id="nome_itm" 
                       name="nome_itm" 
                       value="{{$itens->nome_itm or old('nome_itm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_itm">Descrição:</label>
                <input type="text" class="form-control" id="descricao_itm" 
                       name="descricao_itm" 
                       value="{{$itens->descricao_itm or old('descricao_itm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="preco_itm">Preço:</label>
                <input type="text" class="form-control" id="preco_itm" 
                       name="preco_itm" 
                       value="{{$itens->preco_itm or old('preco_itm')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="peso_itm">Peso(Kg):</label>
                <input type="text" class="form-control" id="peso_itm" 
                       name="peso_itm" 
                       value="{{$itens->peso_itm or old('peso_itm')}}"
                       required>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/magias_list.blade.php
@extends('adminlte::page')

@section('content_header')
  
<div class='col-sm-2'>
    <a href='{{route('magias.create')}}' class='btn btn-primary' 
       role='button'> Novo </a>
       </div>
<div class='col-sm-11'>
        <h2>Magias</h2>
    </div>
    <div class="col-sm-12">
        <table class="table table-striped">
        <thead>
        <tr>
          <th width="200px">Nome</th>
          <th>Descrição</th>
          <th width="235px">Ações</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($magias as $mag)
            <tr>
              <td>{{$mag->nome_mag}}</td>
              <td>{{$mag->descricao_mag}}</td>
              <td>
            
            <a href='{{route('magias.show',$mag->id)}}'
               class='btn btn-info' 
               role='button'> Detalhes </a> 

            <a href='{{route('magias.edit',$mag->id)}}'
               class='btn btn-warning' 
               role='button'> Alterar </a> 

            <form style="display: inline-block"
                  method="post"
                  action="{{route('magias.destroy', $mag->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="submit"
                        class="btn btn-danger"> Deletar </button>
            </form>
            </td>

              </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop   

resources/views/admin/pericias_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Perícia</h2>
    @else 
    <h2> Alteração de Perícia </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('pericias.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('pericias.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('pericias.update', $peric->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_per">Nome:</label>
                <input type="text" class="form-control" id="nome_per" 
                       name="nome_per" 
                       value="{{$peric->nome_per or old('nome_per')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_per">Descrição:</label>
                <input type="text" class="form-control" id="descricao_per" 
                       name="descricao_per" 
                       value="{{$peric->descricao_per or old('descricao_per')}}"
                       required>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/pericias_list.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-2'>
    <a href='{{route('pericias.create')}}' class='btn btn-primary' 
       role='button'> Novo </a>
       </div>
<div class='col-sm-11'>
        <h2>Perícias</h2>
    </div>
    
    <div class="col-sm-12">
        <table class="table table-striped">
        <thead>
        <tr>
          <th width="200px">Nome</th>
          <th>Descrição</th>
          <th width="235px">Ações</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($peric as $per)
            <tr>
              <td>{{$per->nome_per}}</td>
              <td>{{$per->descricao_per}}</td>
              <td>
            
            <a href='{{route('pericias.show',$per->id)}}'
               class='btn btn-info' 
               role='button'> Detalhes </a> 

            <a href='{{route('pericias.edit',$per->id)}}'
               class='btn btn-warning' 
               role='button'> Alterar </a> 

            <form style="display: inline-block"
                  method="post"
                  action="{{route('pericias.destroy',$per->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="submit"
                        class="btn btn-danger"> Deletar </button>
            </form>
            </td>

              </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop   

resources/views/admin/pericias_view.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-10'></div>
<div class='col-sm-2'>
    <a href="{{route('pericias.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
    <div>
        <div class='col-sm-12'>
            <h2> Detalhes da Pericia</h2>
            <p><b>ID: </b> {{$peric->id}}</p>
            <p><b>Nome: </b> {{$peric->nome_per}}</p>
            <p><b>Descrição: </b> {{$peric->descricao_per}}</p>
            </div>
    </div>
@endsection

resources/views/admin/proficiencias_form.blade.php
@extends('adminlte::page')
@section('content_header')
<div class='col-sm-11'>
    @if ($opc == 1)
    <h2> Cadastro de Proficiência</h2>
    @else 
    <h2> Alteração de Proficiência </h2>
    @endif
</div>
<div class='col-sm-1'>
    <a href="{{route('proficiencias.index')}}" class='btn btn-primary' 
       role='button'> Voltar </a>
</div>
<div class="col-sm-12">
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif    
</div>
<div class='col-sm-12'>
    @if ($opc == 1)
    <form method="post" action="{{route('proficiencias.store')}}" enctype="multipart/form-data">
        @else 
        <form method="post" action="{{route('proficiencias.update', $profic->id)}}" enctype="multipart/form-data">
            {!! method_field('put') !!}
            @endif
            {{ csrf_field() }}

            <div class="form-group">
                <label for="nome_pro">Nome:</label>
                <input type="text" class="form-control" id="nome_pro" 
                       name="nome_pro" 
                       value="{{$profic->nome_pro or old('nome_pro')}}"
                       required>
            </div>
            <div class="form-group">
                <label for="descricao_pro">Descrição:</label>
                <input type="text" class="form-control" id="descricao_pro" 
                       name="descricao_pro" 
                       value="{{$profic->descricao_pro or old('descricao_pro')}}"
                       required>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>     
            </div>
        </form>
        @endsection

resources/views/admin/proficiencias_list.blade.php
@extends('adminlte::page')

@section('content_header')
    
<div class='col-sm-2'>
    <a href='{{route('proficiencias.create')}}' class='btn btn-primary' 
       role='button'> Novo </a>
       </div>
<div class='col-sm-11'>
        <h2>Proficiências</h2>
    </div>
    
    <div class="col-sm-12">
        <table class="table table-striped">
        <thead>
        <tr>
          <th width="200px">Nome</th>
          <th>Descrição</th>
          <th width="235px">Ações</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($profic as $prof)
            <tr>
              <td>{{$prof->nome_pro}}</td>
              <td>{{$prof->descricao_pro}}</td>
              <td>
            
            <a href='{{route('proficiencias.show',$prof->id)}}'
               class='btn btn-info' 
               role='button'> Detalhes </a> 

            <a href='{{route('proficiencias.edit',$prof->id)}}'
               class='btn btn-warning' 
               role='button'> Alterar </a> 

            <form style="display: inline-block"
                  method="post"
                  action="{{route('proficiencias.destroy',$prof->id)}}"
                  onsubmit="return confirm('Confirma Exclusão?')">
                {{ method_field('delete') }}
                {{ csrf_field() }}
                <button type="submit"
                        class="btn btn-danger"> Deletar </button>
            </form>
            </td>

              </tr>
            @endforeach
        </tbody>
    </table>
</div>
@stop   